title: Dapur Kelasabil
description: Sebuah ruang publik di **Kelasabil.com** bagian belakang dimana para chef berkumpul :D
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
